### ISSUE TITLE
Support Postcss 8

### ISSUE THREAD

**Issue by zmagauina-fn** [csstools/postcss-extend-rule#13]
Postcss 8 is out, [this](https://evilmartians.com/chronicles/postcss-8-plugin-migration) is its migration guide. Are there any plans to update this?

**Comment by pm64** [comment]
npm actually now reports 2 security vulnerabilities related to postcss-extend-rule due to the outdated PostCSS dependency. The issue is patched in PostCSS >= 8.2.10. Here is some more info:

Regular Expression Denial of Service
postcss-extend-rule > postcss
postcss-extend-rule > postcss-nesting > postcss
https://npmjs.com/advisories/1693

**Comment by Antonio-Laguna** [comment]
This was released as 4.0.0
